### ISSUE TITLE
Change Red Rifle Infantry Model

### ISSUE THREAD

**Issue by MobiSev** [chandawg/RSR-Syria#12]
The unit used for rifle infantry on the red side does not have animation and is constantly crouching.

**Comment by MobiSev** [comment]
I believe the correct model is named "Infantry AK".  The incorrect model and the one that is currently in the server is "Soldier AK"

**Comment by MobiSev** [comment]
Also, I think the only thing that needs to change to fix this is line #2376 in CTLD.lua

**Current code at line #2376:**
                _troops = ctld.insertIntoTroopsArray("Infantry AK", _countOrTemplate.inf, _troops)
            end
        end

New code needs to be:
       _troops = ctld.insertIntoTroopsArray("Infantry AK", _countOrTemplate.inf, _troops)
            end
        end

**Comment by chandawg** [comment]
Will do this evening once kids are in bed, good fix.

**Comment by MobiSev** [comment]
I went ahead and fixed it.

**Comment by chandawg** [comment]
where is the code?
